# [[redirects]]
#   from = "/js/app.js"
#   to = "/js/app.951abf78.js"
#   status = 301
#   force = true

# [[redirects]]
#   from = "/css/app.css"
#   to = "/css/app.96585e57.css"
#   status = 301
#   force = true
